import { Nav } from '@/components/shared/index'
import type { Metadata } from 'next'
// import { Suspense } from 'react'

export const metadata: Metadata = {
	title: 'Rus-autovaz | Корзина',
	description: 'Generated by create next app',
}

export default function CheckoutLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<main className='min-h-screen flex flex-col bg-[#ececec]'>
			{/* <Suspense> */}
			<Nav hasSearch={false} className='border-b-gray-200' />
			{/* </Suspense> */}
			{children}
		</main>
	)
}
